import { useEffect, useMemo, useRef, useState } from 'react';
import type { PointerEvent as ReactPointerEvent } from 'react';
import { buildSegments, generateGcode } from '../lib/diw-gcode';
import { cellKey, DEFAULT_PROFILE, type Direction, type DrawMode, type DrawingDocument, type Magnetization2D, type Point, type Stroke, type DiwPrinterProfile } from '../types/platform';

const initialDoc: DrawingDocument = { version: 1, widthMm: 100, heightMm: 100, strokes: [] };
const initialGrid: Magnetization2D = { version: 1, columns: 12, rows: 12, cells: {} };

function download(name: string, content: string) { const url = URL.createObjectURL(new Blob([content], { type: 'text/plain' })); const anchor = document.createElement('a'); anchor.href = url; anchor.download = name; anchor.click(); URL.revokeObjectURL(url); }
function pointFromEvent(event: ReactPointerEvent<SVGSVGElement>, svg: SVGSVGElement): Point { return pointFromClient(event.clientX, event.clientY, svg); }
function pointFromClient(clientX: number, clientY: number, svg: SVGSVGElement): Point { const matrix = svg.getScreenCTM(); if (!matrix) return { x: 0, y: 0 }; const point = new DOMPoint(clientX, clientY).matrixTransform(matrix.inverse()); return { x: Math.max(0, Math.min(100, point.x)), y: Math.max(0, Math.min(100, point.y)) }; }
function cellFromPoint(point: Point, grid: Magnetization2D) { return { x: Math.min(grid.columns - 1, Math.floor((point.x / 100) * grid.columns)), y: Math.min(grid.rows - 1, Math.floor((point.y / 100) * grid.rows)) }; }
function resizeGrid(grid: Magnetization2D, size: number): Magnetization2D { const cells = Object.fromEntries(Object.entries(grid.cells).filter(([key]) => { const [x, y] = key.split(':').map(Number); return x < size && y < size; })); return { ...grid, columns: size, rows: size, cells }; }
function displacement(point: Point, grid: Magnetization2D, playing: boolean): Point {
  if (!playing) return point;
  let dx = 0; let dy = 0; const cellW = 100 / grid.columns; const cellH = 100 / grid.rows;
  Object.entries(grid.cells).forEach(([key, cell]) => { const [x, y] = key.split(':').map(Number); const cx = (x + 0.5) * cellW; const cy = (y + 0.5) * cellH; const influence = Math.max(0, 1 - Math.hypot(point.x - cx, point.y - cy) / (Math.max(cellW, cellH) * 2.4)); const amplitude = (cell.strength / 100) * influence * 1.8; if (cell.direction.startsWith('X')) dx += (cell.direction === 'X+' ? 1 : -1) * amplitude; if (cell.direction.startsWith('Y')) dy += (cell.direction === 'Y+' ? 1 : -1) * amplitude; });
  return { x: Math.max(0, Math.min(100, point.x + dx)), y: Math.max(0, Math.min(100, point.y + dy)) };
}

export function TouchStudio() {
  const [doc, setDoc] = useState(initialDoc); const [grid, setGrid] = useState(initialGrid); const [profile, setProfile] = useState<DiwPrinterProfile>(DEFAULT_PROFILE); const [drawMode, setDrawMode] = useState<DrawMode>('fill'); const [direction, setDirection] = useState<Direction>('Y+'); const [strength, setStrength] = useState(50); const [activeTab, setActiveTab] = useState<'draw' | 'magnet' | 'preview'>('draw'); const [playing, setPlaying] = useState(false); const [currentStroke, setCurrentStroke] = useState<Point[] | null>(null); const svgRef = useRef<SVGSVGElement>(null); const pointerId = useRef<number | null>(null); const lastGridCell = useRef<string | null>(null); const activeStroke = useRef<Point[] | null>(null); const gridRef = useRef(grid); const activeTabRef = useRef(activeTab); const directionRef = useRef(direction); const strengthRef = useRef(strength); const drawModeRef = useRef(drawMode);
  gridRef.current = grid; activeTabRef.current = activeTab; directionRef.current = direction; strengthRef.current = strength; drawModeRef.current = drawMode;
  const segments = useMemo(() => buildSegments(doc, grid, profile), [doc, grid, profile]); const gcode = useMemo(() => generateGcode(segments, profile), [segments, profile]); const selectedCount = Object.keys(grid.cells).length; const shape = [...doc.strokes, ...(currentStroke ? [{ points: currentStroke, width: drawMode === 'fill' ? 8 : 2.4, mode: drawMode } as Stroke] : [])];
  const toggleCell = (x: number, y: number) => setGrid((old) => { const key = cellKey(x, y); const cells = { ...old.cells }; if (cells[key]?.direction === direction && cells[key]?.strength === strength) delete cells[key]; else cells[key] = { direction, strength }; return { ...old, cells }; });
  const startDrawing = (event: ReactPointerEvent<SVGSVGElement>) => { if (event.button !== 0 || pointerId.current !== null) return; event.preventDefault(); const point = pointFromEvent(event, svgRef.current!); pointerId.current = event.pointerId; if (activeTab === 'magnet') { const cell = cellFromPoint(point, grid); lastGridCell.current = cellKey(cell.x, cell.y); toggleCell(cell.x, cell.y); } else { activeStroke.current = [point]; setCurrentStroke([point]); } };
  useEffect(() => {
    const move = (event: PointerEvent) => { if (pointerId.current !== event.pointerId || !svgRef.current) return; event.preventDefault(); const point = pointFromClient(event.clientX, event.clientY, svgRef.current); if (activeTabRef.current === 'magnet') { const cell = cellFromPoint(point, gridRef.current); const key = cellKey(cell.x, cell.y); if (key !== lastGridCell.current) { lastGridCell.current = key; setGrid((old) => { const cells = { ...old.cells }; const current = cells[key]; if (current?.direction === directionRef.current && current?.strength === strengthRef.current) delete cells[key]; else cells[key] = { direction: directionRef.current, strength: strengthRef.current }; return { ...old, cells }; }); } } else if (activeStroke.current) { const next = [...activeStroke.current, point]; activeStroke.current = next; setCurrentStroke(next); } };
    const finish = (event: PointerEvent) => { if (pointerId.current !== event.pointerId) return; event.preventDefault(); pointerId.current = null; lastGridCell.current = null; const stroke = activeStroke.current; activeStroke.current = null; setCurrentStroke(null); if (activeTabRef.current === 'draw' && stroke && stroke.length >= 2) setDoc((old) => ({ ...old, strokes: [...old.strokes, { points: stroke, width: drawModeRef.current === 'fill' ? 8 : 2.4, mode: drawModeRef.current }] })); };
    const cancel = (event: PointerEvent) => finish(event);
    window.addEventListener('pointermove', move, { passive: false }); window.addEventListener('pointerup', finish, { passive: false }); window.addEventListener('pointercancel', cancel, { passive: false });
    return () => { window.removeEventListener('pointermove', move); window.removeEventListener('pointerup', finish); window.removeEventListener('pointercancel', cancel); };
  }, []);
  const updateProfile = (key: keyof DiwPrinterProfile, value: number | boolean) => setProfile((old) => ({ ...old, [key]: value } as DiwPrinterProfile));
  const updateGridSize = (value: number) => { const next = Math.max(2, Math.min(80, Math.round(value) || 2)); setGrid((old) => resizeGrid(old, next)); };
  const renderStroke = (stroke: Stroke, index: number, deform = false) => <polyline key={index} points={stroke.points.map((point) => { const moved = displacement(point, grid, deform); return `${moved.x},${moved.y}`; }).join(' ')} fill="none" stroke={stroke.mode === 'fill' ? '#e45e43' : '#173f5f'} strokeWidth={stroke.width / 2} strokeLinecap="round" strokeLinejoin="round" opacity={deform ? 0.95 : 1} />;
  return <main className="studio-shell">
    <header className="topbar"><div><span className="eyebrow">4D-DRAWING / PUBLIC DEMO</span><h1>手绘 4D 打印工作站</h1></div><div className="header-status"><span className="status-dot" /> 展示模式 · 尚未连接打印机</div></header>
    <div className="stepbar">{[['draw', '01 画图'], ['magnet', '02 充磁设计'], ['preview', '03 形变与打印']].map(([key, label], index) => <button key={key} className={activeTab === key ? 'step active' : 'step'} onClick={() => setActiveTab(key as typeof activeTab)}><b>{label}</b><small>{index === 0 ? '用手指绘制图案' : index === 1 ? '在图形上定义方向' : '查看路径并导出'}</small></button>)}</div>
    <section className="workspace">
      <aside className="panel controls"><div className="panel-heading"><span className="kicker">WORKSPACE</span><h2>{activeTab === 'draw' ? '画出你的形状' : activeTab === 'magnet' ? '在图形上充磁' : '准备 DIW 打印'}</h2></div>
        {activeTab === 'draw' && <><div className="segmented"><button className={drawMode === 'fill' ? 'selected' : ''} onClick={() => setDrawMode('fill')}>填充涂鸦</button><button className={drawMode === 'stroke' ? 'selected' : ''} onClick={() => setDrawMode('stroke')}>线条绘制</button></div><p className="hint">在画布上拖动手指，完成一笔后抬起，再继续下一笔。</p><button className="outline-button" onClick={() => { setDoc(initialDoc); setGrid(initialGrid); }}>清空画布</button><div className="metric-row"><span>笔划</span><strong>{doc.strokes.length}</strong></div></>}
        {activeTab === 'magnet' && <><p className="hint">手绘图形会保留在网格下方。点击或拖动图形覆盖的网格单元设置或取消充磁。</p><div className="grid-size-fields"><label>正方形网格边长<input type="number" min="2" max="80" value={grid.columns} onChange={(event) => updateGridSize(Number(event.target.value))} /></label></div><label className="field-label">磁场强度 <strong>{strength} <small>控制等级</small></strong><input type="range" min="10" max="100" step="10" value={strength} onChange={(event) => setStrength(Number(event.target.value))} /></label><div className="direction-grid">{(['X+', 'X-', 'Y+', 'Y-'] as Direction[]).map((item) => <button key={item} className={direction === item ? 'direction selected' : 'direction'} onClick={() => setDirection(item)}><span>{item.startsWith('X') ? '↔' : '↕'}</span>{item}</button>)}</div><div className="metric-row"><span>已设计单元</span><strong>{selectedCount} / {grid.columns * grid.rows}</strong></div></>}
        {activeTab === 'preview' && <><p className="hint">形变采用局部磁响应位移场演示：方向决定位移轴，强度决定幅度，距离决定影响衰减。实际材料参数接入后可替换为实验位移场。</p><button className={playing ? 'primary-button playing' : 'primary-button'} onClick={() => setPlaying(!playing)}>{playing ? '暂停形变动画' : '播放形变动画'}</button><button className="outline-button" onClick={() => download('4d-drawing-motion.gcode', generateGcode(segments, { ...profile, emitExtrusion: false }))}>下载无 E 运动版</button><button className="outline-button" onClick={() => download('4d-drawing-diw.gcode', gcode)}>下载 DIW 打印版</button></>}
        <div className="profile-box"><div className="profile-title"><span>DIW PROFILE</span><small>可调整设备参数</small></div><div className="profile-grid"><label>平台 X<input type="number" value={profile.bedWidthMm} onChange={(e) => updateProfile('bedWidthMm', Number(e.target.value))} /></label><label>平台 Y<input type="number" value={profile.bedHeightMm} onChange={(e) => updateProfile('bedHeightMm', Number(e.target.value))} /></label><label>喷嘴直径<input type="number" step="0.01" value={profile.nozzleDiameterMm} onChange={(e) => updateProfile('nozzleDiameterMm', Number(e.target.value))} /></label><label>线宽<input type="number" step="0.01" value={profile.lineWidthMm} onChange={(e) => updateProfile('lineWidthMm', Number(e.target.value))} /></label><label>层高 Z<input type="number" step="0.1" value={profile.layerHeightMm} onChange={(e) => updateProfile('layerHeightMm', Number(e.target.value))} /></label><label>速度 mm/min<input type="number" value={profile.speedMmMin} onChange={(e) => updateProfile('speedMmMin', Number(e.target.value))} /></label><label>路径角度<input type="number" min="-180" max="180" step="15" value={profile.pathAngleDeg} onChange={(e) => updateProfile('pathAngleDeg', Number(e.target.value))} /></label></div><label className="check-row"><input type="checkbox" checked={profile.emitExtrusion} onChange={(e) => updateProfile('emitExtrusion', e.target.checked)} /> 输出 E 轴挤出量</label></div>
      </aside>
      <section className="canvas-column"><div className="canvas-card"><div className="canvas-toolbar"><span><i className="live-dot" />{activeTab === 'draw' ? '触摸画板' : activeTab === 'magnet' ? '图形磁化网格' : '局部形变预览'}</span><span className="canvas-meta">100 × 100 mm</span></div><svg ref={svgRef} className="drawing-canvas" style={{ touchAction: 'none' }} viewBox="0 0 100 100" onPointerDown={startDrawing} aria-label="触摸绘画画布"><defs><pattern id="grid" width={100 / grid.columns} height={100 / grid.rows} patternUnits="userSpaceOnUse"><path d={`M ${100 / grid.columns} 0 L 0 0 0 ${100 / grid.rows}`} fill="none" stroke="#d9e1e7" strokeWidth="0.25" /></pattern></defs><rect width="100" height="100" fill="#fbfcfa" />{activeTab !== 'draw' && shape.map((stroke, index) => renderStroke(stroke, index, activeTab === 'preview' && playing))}{activeTab !== 'draw' && <rect width="100" height="100" fill="url(#grid)" />}{activeTab === 'magnet' && Object.entries(grid.cells).map(([key, cell]) => { const [x, y] = key.split(':').map(Number); return <rect key={key} x={x * 100 / grid.columns} y={y * 100 / grid.rows} width={100 / grid.columns} height={100 / grid.rows} className={`cell-${cell.direction.replace('+', 'plus').replace('-', 'minus')}`} opacity={0.35 + cell.strength / 200} />; })}{activeTab === 'draw' && shape.map((stroke, index) => renderStroke(stroke, index))}{activeTab === 'preview' && segments.map((segment, index) => <line key={index} x1={segment.start.x} y1={segment.start.y} x2={segment.end.x} y2={segment.end.y} stroke="#da7b3c" strokeWidth={profile.lineWidthMm / 2} opacity="0.9" />)}</svg></div><div className="canvas-caption"><span><b>{activeTab === 'preview' ? segments.length : activeTab === 'magnet' ? selectedCount : doc.strokes.length}</b> {activeTab === 'preview' ? '条沉积路径' : activeTab === 'magnet' ? '个磁化单元' : '笔已完成'}</span><span>{playing ? '磁响应进行中' : '准备就绪'}</span></div></section>
      <aside className="panel insight"><div className="panel-heading"><span className="kicker">LIVE EXPLANATION</span><h2>{activeTab === 'preview' ? '从图案到动作' : '让磁场看得见'}</h2></div><div className="legend"><div><span className="swatch orange" />磁化沉积路径</div><div><span className="swatch blue" />方向与强度设置</div><div><span className="swatch green" />局部位移区域</div></div><div className="stats"><div><small>网格规格</small><strong>{grid.columns} × {grid.rows}</strong></div><div><small>路径长度</small><strong>{segments.reduce((sum, s) => sum + Math.hypot(s.end.x - s.start.x, s.end.y - s.start.y), 0).toFixed(1)} <em>mm</em></strong></div><div><small>磁化事件</small><strong>{segments.length ? new Set(segments.map((s) => `${s.strength}-${s.direction}`)).size : 0}</strong></div></div><div className="explain-card"><span className="card-icon">✦</span><div><strong>{activeTab === 'draw' ? '从一笔开始' : activeTab === 'magnet' ? '先看图形，再选网格' : '位移场驱动形变'}</strong><p>{activeTab === 'draw' ? '你的手绘会被转换为可追踪的毫米坐标。完成后进入充磁设计。' : activeTab === 'magnet' ? '图形始终保留在网格下方，磁化区域可以直接对应到手绘形状。' : '这是可替换的参数化模型，不代表已完成材料标定；真实预测需要弹性、磁化和外场数据。'}</p></div></div><div className="safe-note"><span>✓</span><p>安全状态：G-code 始终以 <code>MAG_OFF</code> 结束，不包含温控命令。</p></div></aside>
    </section>
    <footer className="footer"><span>4D-DRAWING STUDIO · 科普展示原型 v0.1</span><span>工作人员确认后连接打印机</span></footer>
  </main>;
}
